version: '3.8'

services:
  drupal:
    image: drupal:${DRUPAL_VERSION}
    restart: always
    ports:
      - ${DRUPAL_PORT}:80
    expose:
      - 80
    volumes:
      - './www:/var/www/html'
    networks:
      - drupal
  database:
    image: mysql:${MYSQL_VERSION}
    restart: always
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - 'database:/var/lib/mysql'
    networks:
      - drupal

volumes:
  database:
networks:
  drupal: